.PHONY: all clean

all:
	$(MAKE) -C problem-1
	$(MAKE) -C problem-2
	$(MAKE) -C problem-3
	$(MAKE) -C problem-4

clean:
	$(MAKE) -C problem-1 clean
	$(MAKE) -C problem-2 clean
	$(MAKE) -C problem-3 clean
	$(MAKE) -C problem-4 clean
