.PHONY: all clean

all:
	$(MAKE) -C problem-1
	$(MAKE) -C problem-2
	$(MAKE) -C problem-3
	$(MAKE) -C problem-4
	$(MAKE) -C problem-5
	$(MAKE) -C problem-6
	$(MAKE) -C problem-7
	$(MAKE) -C problem-8
	$(MAKE) -C problem-9
	$(MAKE) -C problem-10
	$(MAKE) -C problem-11
	$(MAKE) -C problem-12
	$(MAKE) -C problem-13

clean:
	$(MAKE) -C problem-1 clean
	$(MAKE) -C problem-2 clean
	$(MAKE) -C problem-3 clean
	$(MAKE) -C problem-4 clean
	$(MAKE) -C problem-5 clean
	$(MAKE) -C problem-6 clean
	$(MAKE) -C problem-7 clean
	$(MAKE) -C problem-8 clean
	$(MAKE) -C problem-9 clean
	$(MAKE) -C problem-10 clean
	$(MAKE) -C problem-11 clean
	$(MAKE) -C problem-12 clean
	$(MAKE) -C problem-13 clean
