name: build

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build project
        run: make
